apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: june23-novllm-2
  janus-idp.io/tekton: june23-novllm-2
  backstage.io/kubernetes-id: june23-novllm-2
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: june23-novllm-2
resources:
  - initialize-namespace/
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
